plugins {
	alias libs.plugins.fabric.loom
	alias libs.plugins.repositories
}

dependencies {
	minecraft libs.minecraft
	mappings(loom.layered {
		it.officialMojangMappings()
		it.parchment("org.parchmentmc.data:parchment-${libs.versions.parchment.minecraft.get()}:${libs.versions.parchment.mappings.get()}@zip")
	})
	compileOnly projects.sparkweaveCommon

	compileOnly libs.autoservice.annotations
	annotationProcessor libs.autoservice

	modImplementation libs.fabric.loader
	modImplementation libs.fabric.api

	implementation(projects.sparkweaveCommon) {
		capabilities {
			it.requireFeature("renderdoc-loader")
		}
		endorseStrictVersions()

		transitive = false
	}
	include(projects.sparkweaveCommon) {
		capabilities {
			it.requireFeature("renderdoc-loader")
		}

		transitive = false
	}

	testmodImplementation sourceSets.main.output
	testmodCompileOnly(projects.sparkweaveCommon) {
		targetConfiguration = "testmod"
	}
	testmodCompileOnly libs.autoservice.annotations
	testmodAnnotationProcessor libs.autoservice

//	modImplementation (libs.resourcefulconfig.fabric) {
//		transitive = false
//	}

	implementation libs.appdirs
	include libs.appdirs

	modCompileOnly(variantOf(libs.emi.fabric) { classifier 'api' }) {
		transitive = false
	}
	modLocalRuntime (libs.emi.fabric) {
		transitive = false
	}

	modCompileOnly (libs.modmenu.fabric) {
		transitive = false
	}
	modLocalRuntime (libs.modmenu.fabric) {
		transitive = false
	}

	testImplementation libs.junit.api
	testImplementation libs.neoforge.testframework
	testRuntimeOnly libs.junit.launcher
	testRuntimeOnly libs.junit.engine
}

test {
	useJUnitPlatform()
}

def rp = rootProject
loom {
	mods {
		"${mod_id}" {
			// Tell Loom about each source set used by your mod here. This ensures that your mod's classes are properly transformed by Loader.
			sourceSet sourceSets.main
			sourceSet projects.sparkweaveCommon.dependencyProject.sourceSets.main
		}

		"${mod_id}_testmod" {
			sourceSet sourceSets.testmod
			sourceSet projects.sparkweaveCommon.dependencyProject.sourceSets.testmod
		}
	}

	accessWidenerPath.set(file("src/main/resources/${mod_id}.accesswidener"))

	mixin {
		useLegacyMixinAp.set(false)
	}

	runs {
		configureEach {
			ideConfigGenerated(true)
			it.property('sparkweave.debug', 'true')
			it.property('mixin.debug', 'true')
		}

		client {
			client()
			setConfigName("Fabric Client")
			runDir("run")

			if (project.hasProperty('mc_uuid')) {
				programArg("--uuid=${project.findProperty('mc_uuid')}")
			}

			if (project.hasProperty('mc_username')) {
				programArg("--username=${project.findProperty('mc_username')}")
			}

			if (project.hasProperty('mc_java_agent_path')) {
				vmArg("-javaagent:${project.findProperty('mc_java_agent_path')}")
			}
		}

		clientRenderDoc {
			client()
			setConfigName("Fabric ClientRenderDoc")
			runDir("run")
			property("${project.mod_id}.debug.render.load_renderdoc", 'true')

			if (project.hasProperty('mc_uuid')) {
				programArg("--uuid=${project.findProperty('mc_uuid')}")
			}

			if (project.hasProperty('mc_username')) {
				programArg("--username=${project.findProperty('mc_username')}")
			}

			if (project.hasProperty('mc_java_agent_path')) {
				vmArg("-javaagent:${project.findProperty('mc_java_agent_path')}")
			}
		}

		testmodClient {
			client()
			setConfigName("Fabric Testmod Client")
			runDir("run/testmod")
			source(sourceSets.testmod)

			if (project.hasProperty('mc_uuid')) {
				programArg("--uuid=${project.findProperty('mc_uuid')}")
			}

			if (project.hasProperty('mc_username')) {
				programArg("--username=${project.findProperty('mc_username')}")
			}

			if (project.hasProperty('mc_java_agent_path')) {
				vmArg("-javaagent:${project.findProperty('mc_java_agent_path')}")
			}
		}

		server {
			server()
			setConfigName("Fabric Server")
			runDir("run/server")
		}

		datagen {
			client()
			setConfigName("Fabric Data Generation")

			source(sourceSets.testmod)

			property("fabric-api.datagen")
			property("fabric-api.datagen.strict-validation", "true") // '--all' sets '--validate' to true as well
			property("fabric-api.datagen.output-dir", file("src/testmod/generated").absolutePath)
			property("sparkweave.datagen.mods", "${mod_id}, ${mod_id}_testmod")
			runDir("build/datagen")
		}
	}
}

tasks.register('generateDatagenDir') {
	inputs.dir(project.layout.buildDirectory.dir("datagen"))

	doFirst {
		inputs.files.forEach { it.mkdirs() }
	}
}

tasks.ideaSyncTask.finalizedBy(tasks.generateDatagenDir)
tasks.runDatagen.dependsOn(tasks.generateDatagenDir)
sourceSets.testmod.resources { srcDir "src/testmod/generated" }

tasks.named("compileJava", JavaCompile) {
	source projects.sparkweaveCommon.dependencyProject.sourceSets.main.allJava
}

tasks.named("compileTestJava", JavaCompile) {
	source projects.sparkweaveCommon.dependencyProject.sourceSets.test.allJava
}

tasks.named("compileTestmodJava", JavaCompile).configure {
	source projects.sparkweaveCommon.dependencyProject.sourceSets.testmod.allJava
}

tasks.named("javadoc", Javadoc).configure {
	source projects.sparkweaveCommon.dependencyProject.sourceSets.main.allJava
}

tasks.named("sourcesJar", Jar) {
	from projects.sparkweaveCommon.dependencyProject.sourceSets.main.allSource
}

processResources {
	from projects.sparkweaveCommon.dependencyProject.sourceSets.main.resources
}

processTestResources {
	from projects.sparkweaveCommon.dependencyProject.sourceSets.test.resources
}

processTestmodResources {
	from projects.sparkweaveCommon.dependencyProject.sourceSets.testmod.resources
}
