plugins {
	alias fabric.plugins.fabric.loom
	alias libs.plugins.repositories
}

dependencies {
	minecraft libs.minecraft
	mappings(loom.layered {
		it.officialMojangMappings()
		it.parchment("org.parchmentmc.data:parchment-${libs.versions.parchment.minecraft.get()}:${libs.versions.parchment.mappings.get()}@zip")
	})
	compileOnly project(":Common")

	modImplementation fabric.fabric.loader
	modImplementation fabric.fabric.api

	testmodImplementation sourceSets.main.output
	testmodCompileOnly project(path: ":Common", configuration: "testmod")

//	modImplementation (libs.resourcefulconfig.fabric) {
//		transitive = false
//	}

	implementation libs.appdirs
	include libs.appdirs

	modCompileOnly(variantOf(libs.emi.fabric) { classifier 'api' }) {
		transitive = false
	}
//	modLocalRuntime (libs.emi.fabric) {
//		transitive = false
//	}

	modCompileOnly (fabric.modmenu) {
		transitive = false
	}
	modLocalRuntime (fabric.modmenu) {
		transitive = false
	}

	testImplementation libs.junit.api
	testImplementation neoforge.testframework
	testRuntimeOnly libs.junit.launcher
	testRuntimeOnly libs.junit.engine
}

test {
	useJUnitPlatform()
}

loom {
	mods {
		"${mod_id}" {
			// Tell Loom about each source set used by your mod here. This ensures that your mod's classes are properly transformed by Loader.
			sourceSet sourceSets.main
			sourceSet project(":Common").sourceSets.main
		}

		"${mod_id}_testmod" {
			sourceSet sourceSets.testmod
			sourceSet project(":Common").sourceSets.testmod
		}
	}

	accessWidenerPath.set(file("src/main/resources/${mod_id}.accesswidener"))

	mixin {
		defaultRefmapName.set("${mod_id}.refmap.json")
	}

	runs {
		configureEach {
			it.property('sparkweave.debug', 'true')
		}

		client {
			client()
			setConfigName("Fabric Client")
			ideConfigGenerated(true)
			runDir("run")

			if (project.hasProperty('mc_uuid')) {
				programArg("--uuid=${project.findProperty('mc_uuid')}")
			}

			if (project.hasProperty('mc_username')) {
				programArg("--username=${project.findProperty('mc_username')}")
			}

			if (project.hasProperty('mc_java_agent_path')) {
				vmArg("-javaagent:${project.findProperty('mc_java_agent_path')}")
			}
		}

		testmodClient {
			client()
			setConfigName("Fabric Testmod Client")
			ideConfigGenerated(true)
			runDir("run/testmod")
			source(sourceSets.testmod)

			if (project.hasProperty('mc_uuid')) {
				programArg("--uuid=${project.findProperty('mc_uuid')}")
			}

			if (project.hasProperty('mc_username')) {
				programArg("--username=${project.findProperty('mc_username')}")
			}

			if (project.hasProperty('mc_java_agent_path')) {
				vmArg("-javaagent:${project.findProperty('mc_java_agent_path')}")
			}
		}

		server {
			server()
			setConfigName("Fabric Server")
			ideConfigGenerated(true)
			runDir("run/server")
		}
	}
}

tasks.named("compileJava", JavaCompile) {
	source(project(":Common").sourceSets.main.allJava)
}

tasks.named("compileTestJava", JavaCompile) {
	source(project(":Common").sourceSets.test.allJava)
}

tasks.named("compileTestmodJava", JavaCompile).configure {
	source(project(":Common").sourceSets.testmod.allJava)
}

tasks.named("javadoc", Javadoc).configure {
	source(project(":Common").sourceSets.main.allJava)
}

tasks.named("sourcesJar", Jar) {
	from(project(":Common").sourceSets.main.allSource)
}

processResources {
	from project(":Common").sourceSets.main.resources
}

processTestResources {
	from project(":Common").sourceSets.test.resources
}

processTestmodResources {
	from project(":Common").sourceSets.testmod.resources
}
