[versions]
# The latest versions are available at https://fabricmc.net/develop
fabric_loom = "1.10.1"

fabric_loader = "0.16.10"
fabric_api = "0.115.1+1.21.1"

# https://quiltmc.org/en/usage/latest-versions
quilt_loader = "0.28.0-beta.8"

# https://modrinth.com/mod/modmenu/versions
modmenu = "11.0.3"

[libraries]
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
