pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net'
		}
		maven {
			name = 'Ladysnake'
			url = 'https://maven.ladysnake.org/releases'
		}
		gradlePluginPortal()
	}
}

plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '0.9.0'
}

rootProject.name = 'Sparkweave'

def ENV = System.getenv()

buildCache {
	remote(HttpBuildCache) {
		url = "https://ci-cache.uuid.gg/cache"
		if (ENV.CI && ENV.GRADLE_BUILD_CACHE_USER && ENV.GRADLE_BUILD_CACHE_TOKEN) {
			push = true
			credentials {
				username = ENV.GRADLE_BUILD_CACHE_USER
				password = ENV.GRADLE_BUILD_CACHE_TOKEN
			}
		}
	}
}
