[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
quilt_loom = "1.7.4"

quilt_loader = "0.26.4-beta.1"
quilted_fabric_api = "11.0.0-alpha.3+0.102.0-1.21"
qsl = "10.0.0-alpha.2+1.21.1"

[libraries]
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

qsl = { module = "org.quiltmc:qsl", version.ref = "qsl" }
quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }
quilted_fabric_api_deprecated = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api-deprecated", version.ref = "quilted_fabric_api" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]
quilted_fabric_api = ["qsl", "quilted_fabric_api"]
quilted_fabric_api_deprecated = ["qsl", "quilted_fabric_api", "quilted_fabric_api_deprecated"]

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version.ref = "quilt_loom" }
