[versions]
chenille = "0.14.0"
fabric_loom = "1.9.2"

minecraft = "1.20.1"
fabric_loader = "0.16.9"

parchment_minecraft = "1.20.1"
parchment_mappings = "2023.09.03"

fabric_api = "0.92.2+1.20.1"
appdirs = "1.2.1"

emi = "1.0.29+1.20.1"
modmenu = "7.2.2"
lazydfu = "0.1.3"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

appdirs = { module = "net.harawata:appdirs", version.ref = "appdirs" }

emi = { module = "dev.emi:emi-fabric", version.ref = "emi" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
lazydfu = { module = "maven.modrinth:lazydfu", version.ref = "lazydfu" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
chenille = { id = "io.github.ladysnake.chenille", version.ref = "chenille" }
