plugins {
	alias libs.plugins.moddevgradle
}


// Vanilla depends on ASM 9.3, MDG makes that a 'strict' version constraint,
// but mixin needs newer ASM so we override that here.
configurations.configureEach {
	resolutionStrategy.eachDependency { details ->
		if(details.requested.group == "org.ow2.asm") {
			details.useVersion(libs.versions.asm.get())
			details.because("Mixin requires new ASM")
		}
	}
}

dependencies {
	implementation libs.bundles.mixin
	compileOnly libs.jetbrains.annotations

	compileOnly libs.appdirs

//	compileOnly libs.resourcefulconfig
	compileOnly variantOf(libs.emi) {
		classifier 'api'
	}

	testmodImplementation sourceSets.main.output
}

neoForge {
	neoFormVersion = libs.versions.neoform.get()

	parchment {
		minecraftVersion = libs.versions.parchment.minecraft.get()
		mappingsVersion = libs.versions.parchment.mappings.get()
	}

	accessTransformers {
		def atFile = file("src/main/resources/META-INF/accesstransformer.cfg")
		from atFile
		publish atFile
	}
}

configurations {
	testmod {
		canBeResolved = false
		canBeConsumed = true
	}
}

artifacts {
	testmod(sourceSets.testmod.output.classesDirs.singleFile) {
		builtBy testmodClasses
	}
}
