plugins {
	alias libs.plugins.moddevgradle
}

dependencies {
	compileOnly libs.bundles.mixin
	compileOnly libs.jetbrains.annotations

	compileOnly libs.appdirs

//	compileOnly libs.resourcefulconfig
	compileOnly variantOf(libs.emi) {
		classifier 'api'
	}

	testmodImplementation sourceSets.main.output

	testCompileOnly libs.junit.api
	testCompileOnly neoforge.testframework
}

neoForge {
	neoFormVersion = libs.versions.neoform.get()

	parchment {
		minecraftVersion = libs.versions.parchment.minecraft.get()
		mappingsVersion = libs.versions.parchment.mappings.get()
	}

	accessTransformers {
		def atFile = file("src/main/resources/META-INF/accesstransformer.cfg")
		from atFile
		publish atFile
	}
	validateAccessTransformers.set(true)

	addModdingDependenciesTo sourceSets.test
}

configurations {
	testmod {
		canBeResolved = false
		canBeConsumed = true
	}
}

artifacts {
	testmod(sourceSets.testmod.output.classesDirs.singleFile) {
		builtBy testmodClasses
	}
}
