[versions]
minecraft = "1.21.1"

# The latest versions are available at https://parchmentmc.org/docs/getting-started
parchment_minecraft = "1.21.1"
parchment_mappings = "2024.11.17"

# https://projects.neoforged.net/neoforged/moddevgradle
moddevgradle = "2.0.78"

# https://projects.neoforged.net/neoforged/neoform
neoform = "1.21.1-20240808.144430"

# minecraft dependencies
jetbrains_annotations = "26.0.2"
mixin = "0.15.5+mixin.0.8.7"
mixin_extras = "0.4.1"
asm = "9.7.1"

# other dependencies
appdirs = "1.2.1"
# https://beehive.sh
resourcefulconfig = "3.0.9"
emi = "1.1.19+1.21.1"

# test dependencies
junit = "5.11.3"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
mixin = { module = "net.fabricmc:sponge-mixin", version.ref = "mixin" }
mixin_extras = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixin_extras" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm_analysis = { module = "org.ow2.asm:asm-analysis", version.ref = "asm" }
asm_commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asm_tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
asm_util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }
jetbrains_annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains_annotations" }

appdirs = { module = "net.harawata:appdirs", version.ref = "appdirs" }

resourcefulconfig = { module = "com.teamresourceful.resourcefulconfig:resourcefulconfig-common-1.21", version.ref = "resourcefulconfig" }
resourcefulconfig_fabric = { module = "com.teamresourceful.resourcefulconfig:resourcefulconfig-fabric-1.21", version.ref = "resourcefulconfig" }
resourcefulconfig_neoforge = { module = "com.teamresourceful.resourcefulconfig:resourcefulconfig-neoforge-1.21", version.ref = "resourcefulconfig" }

emi = { module = "dev.emi:emi-xplat-mojmap", version.ref = "emi" }
emi_neoforge = { module = "dev.emi:emi-neoforge", version.ref = "emi" }
emi_fabric = { module = "dev.emi:emi-fabric", version.ref = "emi" }

junit_api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit_launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit_engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

[bundles]
mixin = ["mixin", "mixin_extras", "asm", "asm_analysis", "asm_commons", "asm_tree", "asm_util"]

[plugins]
moddevgradle = { id = "net.neoforged.moddev", version.ref = "moddevgradle" }
repositories = { id = "net.neoforged.moddev.repositories", version.ref = "moddevgradle" }
