plugins {
	alias libs.plugins.moddevgradle
}

// need this before dependencies because it configures the plugin and creates additionalRuntimeClasspath configuration
neoForge.version = libs.versions.neoforge.get()

configurations {
	runtimeClasspath.extendsFrom localRuntime
}

dependencies {
	compileOnly project(":Common")
	interfaceInjectionData project(":Common")
	accessTransformers project(":Common")
	compileOnly libs.autoservice.annotations
	annotationProcessor libs.autoservice

	compileOnly(project(":Common")) {
		capabilities {
			requireCapability("${rootProject.group}:${rootProject.name}-Common-renderdocLoader:${project.version}")
		}
	}
	localRuntime(project(":Common")) {
		capabilities {
			requireCapability("${rootProject.group}:${rootProject.name}-Common-renderdocLoader:${project.version}")
		}
	}

	testmodImplementation sourceSets.main.output
	testmodCompileOnly project(path: ":Common", configuration: "testmod")
	testmodCompileOnly libs.autoservice.annotations
	testmodAnnotationProcessor libs.autoservice

//	implementation libs.resourcefulconfig.neoforge

	implementation libs.appdirs
	additionalRuntimeClasspath libs.appdirs
	jarJar(libs.appdirs) {
		transitive = false
	}

	compileOnly variantOf(libs.emi.neoforge) {
		classifier 'api'
	}
	localRuntime libs.emi.neoforge

	testImplementation libs.junit.api
	testImplementation libs.neoforge.testframework
	testRuntimeOnly libs.junit.launcher
	testRuntimeOnly libs.junit.engine
}

jar {
	def loaderJarName = "${mod_id}-renderdoc-loader-${version}.jar"
	from(project(":Common").tasks.renderdocJar) {
		into "META-INF/jarjar"
		rename { loaderJarName }
	}
}

test {
	useJUnitPlatform()
}

neoForge {
	parchment {
		minecraftVersion = libs.versions.parchment.minecraft.get()
		mappingsVersion = libs.versions.parchment.mappings.get()
	}

	mods {
		// define mod <-> source bindings
		// these are used to tell the game which sources are for which mod
		// mostly optional in a single mod project
		// but multi mod projects should define one per mod
		"${mod_id}" {
			sourceSet(sourceSets.main)
			sourceSet(project(":Common").sourceSets.main)
		}

		"${mod_id}_renderdoc_loader" {
			sourceSet(project(":Common").sourceSets.renderdoc)
		}

		"${project.mod_id}_testmod" {
			sourceSet(sourceSets.testmod)
			sourceSet(project(":Common").sourceSets.testmod)
		}
	}

	unitTest {
		enable()

		testedMod = mods."${mod_id}"
		loadedMods.set([mods."${mod_id}"])
	}

	runs {
		configureEach {
			logLevel = org.slf4j.event.Level.DEBUG
			systemProperty 'forge.logging.markers', 'REGISTRIES'
			systemProperty 'sparkweave.debug', 'true'

			if (project.hasProperty('mc_java_agent_path')) {
				jvmArgument("-javaagent:${project.findProperty('mc_java_agent_path')}")
			}
		}

		client {
			client()
			devLogin = true
			gameDirectory = project.file('run')
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id

			sourceSet = sourceSets.main
			loadedMods.set([mods."${mod_id}"])
		}

		clientRenderDoc {
			client()
			devLogin = true
			gameDirectory = project.file('run')
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
			systemProperty "${project.mod_id}.debug.render.load_renderdoc", 'true'

			sourceSet = sourceSets.main
			loadedMods.set([mods."${mod_id}", mods."${mod_id}_renderdoc_loader"])
		}

		server {
			server()
			gameDirectory = project.file('run')
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id

			sourceSet = sourceSets.main
			loadedMods.set([mods."${mod_id}"])

			programArguments.add('--nogui')
		}

		testmodClient {
			client()
			devLogin = true
			gameDirectory = project.file('run/testmod')
			systemProperty 'neoforge.enabledGameTestNamespaces', "${project.mod_id}_testmod"

			sourceSet = sourceSets.testmod
			loadedMods.set([mods."${mod_id}", mods."${mod_id}_testmod"])
		}

		data {
			data()
			gameDirectory = project.file('run')
			programArguments.addAll('--mod', "${mod_id}", '--mod', "${mod_id}_testmod", '--all', '--flat', '--output', file('src/testmod/generated').absolutePath, '--existing', file('src/testmod/resources').absolutePath)

			sourceSet = sourceSets.testmod
			loadedMods.set([mods."${mod_id}", mods."${mod_id}_testmod"])
		}
	}
}

sourceSets.testmod.resources { srcDir "src/testmod/generated" }

tasks.named("compileJava", JavaCompile) {
	source project(":Common").sourceSets.main.allJava
}

tasks.named("compileTestJava", JavaCompile) {
	source project(":Common").sourceSets.test.allJava
}

tasks.named("compileTestmodJava", JavaCompile) {
	source project(":Common").sourceSets.testmod.allJava
}

tasks.named("javadoc", Javadoc) {
	source project(":Common").sourceSets.main.allJava
}

tasks.named("sourcesJar", Jar) {
	from project(":Common").sourceSets.main.allSource
}

processResources {
	from project(":Common").sourceSets.main.resources
}

processTestResources {
	from project(":Common").sourceSets.test.resources
}

processTestmodResources {
	from project(":Common").sourceSets.testmod.resources
}
