[versions]
neogradle = "7.0.139"

neoforge = "20.6.111-beta"

[libraries]
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

[plugins]
neogradle = { id = "net.neoforged.gradle.userdev", version.ref = "neogradle" }
