[versions]
neogradle = "7.+"

neoforge = "20.2.88"

[libraries]
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

[plugins]
neogradle = { id = "net.neoforged.gradle.userdev", version.ref = "neogradle" }
