[versions]
moddevgradle = "2.0.16-beta"

neoforge = "21.1.15"

[libraries]
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

[plugins]
moddevgradle = { id = "net.neoforged.moddev", version.ref = "moddevgradle" }
