[versions]
neogradle = "7.0.100"

neoforge = "20.4.235"

[libraries]
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

[plugins]
neogradle = { id = "net.neoforged.gradle.userdev", version.ref = "neogradle" }
