name: Upload Release Artifacts

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: 17
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYYMMDDHHmmss
      - name: Setup ENV
        run: echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Copy Maven Upload URL
        id: extract_maven_upload_url
        run: echo "maven_upload_url=${{secrets.MAVEN_UPLOAD_URL}}" >> $GITHUB_OUTPUT
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        env:
          BUILD_TIME: ${{ steps.current-time.outputs.formattedTime }}
          BUILD_NUMBER: ${{ github.run_number }}
        run: ./gradlew assemble --rerun-tasks
      - name: Maven Release
        if: steps.extract_maven_upload_url.outputs.maven_upload_url
        env:
          BUILD_TIME: ${{ steps.current-time.outputs.formattedTime }}
          BUILD_NUMBER: ${{ github.run_number }}
          MAVEN_UPLOAD_URL: ${{ secrets.MAVEN_UPLOAD_URL }}
          MAVEN_UPLOAD_USERNAME: ${{ secrets.MAVEN_UPLOAD_USERNAME }}
          MAVEN_UPLOAD_PASSWORD: ${{ secrets.MAVEN_UPLOAD_PASSWORD }}
        run: ./gradlew publish
      - name: Publish (GitHub Releases)
        uses: Kir-Antipov/mc-publish@423b200ec84e6eefad726549c72513d7a9b4c2c0 # (new) v3.3
        with:
          github-token: ${{ github.token }}
          version-type: beta
          files: |
            **/build/libs/!(*-@(dev|sources|javadoc|slim)).jar
            **/build/libs/*-@(sources|javadoc).jar
      - name: Publish (Fabric)
        uses: Kir-Antipov/mc-publish@423b200ec84e6eefad726549c72513d7a9b4c2c0 # (new) v3.3
        with:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          version: ${{ github.ref_name }}+Fabric
          version-type: beta
          files: |
            Fabric/build/libs/!(*-@(dev|sources|javadoc|slim)).jar
            Fabric/build/libs/*-@(sources|javadoc).jar
      - name: Publish (NeoForge)
        uses: Kir-Antipov/mc-publish@423b200ec84e6eefad726549c72513d7a9b4c2c0 # (new) v3.3
        with:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          version: ${{ github.ref_name }}+NeoForge
          version-type: beta
          files: |
            NeoForge/build/libs/!(*-@(dev|sources|javadoc|slim)).jar
            NeoForge/build/libs/*-@(sources|javadoc).jar
      - name: Publish (Quilt)
        uses: Kir-Antipov/mc-publish@423b200ec84e6eefad726549c72513d7a9b4c2c0 # (new) v3.3
        with:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          version: ${{ github.ref_name }}+Quilt
          version-type: beta
          files: |
            Quilt/build/libs/!(*-@(dev|sources|javadoc|slim)).jar
            Quilt/build/libs/*-@(sources|javadoc).jar
